name: Test CI

on:
  push:
    branches:
      - master

jobs:
  CI:
    name: Run CI
    runs-on: ubuntu-latest
    steps:
      - uses: appleboy/ssh-action@master
    with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        port: ${{ secrets.SSH_PORT }}
        script: |
          cd var/www/...
          yarn build
          yarn start:prod
